name: okra_lifecycle
description: A farming guide app for okra cultivation in Bengali

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.8.5
  camera: ^0.10.5+7
  permission_handler: ^11.0.1
  url_launcher: ^6.2.1
  flutter_launcher_icons: ^0.13.1
  #tflite_flutter: ^0.10.1  # For TensorFlow Lite

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/ 